version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-biblio}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - biblio_network
  app:
    build: ./docker/
    ports: ['80:80']
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      - biblio_network

networks:
  biblio_network: {}

volumes:
  database_data:
